import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // defaultSidebar: [{type: 'autogenerated', dirName: '.', exclude: ['homepage']}],
  servicesSidebar: [
    {
      type: "category",
      label: "Services",
      // link: { type: "doc", id: "services/services" },
      link: { 
        type: "generated-index", 
        title: "Services",
        description: "Collection of self-hosted service related articles",
        slug: '/services',
        keywords: ['services']
      },
      items: [{ type: "autogenerated", dirName: "services"}],
    },
  ],
  networkingSidebar: [
    {
      type: "category",
      label: "Networking",
      // link: { type: "doc", id: "services/services" },
      link: { 
        type: "generated-index", 
        title: "Networking",
        description: "Building and managing networks",
        slug: '/networking',
        keywords: ['networking']
      },
      items: [{ type: "autogenerated", dirName: "networking"}],
    },
  ]
};

export default sidebars;
